def adminMenu():
    print("Welcome ! Admin Menu:")
    print("1.Add user")
    print("2.Show all user")
    print("3.Add restaurant")
    print("4.Show all restaurant")
    print("5.Edit restaurant")
    print("6.Delete restaurant")
    print("7.Review")
    print("Any other number to exit")
